FROM python:3-alpine
# FROM python:3.11
WORKDIR /app
COPY ./ ./
RUN apk add --no-cache postgresql-libs
RUN apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev
RUN python -m pip install -r requirements.txt
EXPOSE 8000
# CMD python3 manage.py makemigrations ; python3 manage.py migrate ; python3 manage.py runserver 0.0.0.0:8000
CMD python manage.py makemigrations ; python manage.py migrate ; python manage.py runserver 0.0.0.0:8000